name: SonarQube Analysis
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --no-restore
      
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: Build and analyze
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"kovesdinorbert_CodeCheck" /o:"kovesdinorbert" /d:sonar.host.url="${{ secrets.SONAR_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
          
      # - name: create pull request
        # uses: peter-evans/create-pull-request@v3
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # commit-message: 'sonarqube suggested fixes'
          # title: 'sonarqube: javasolt javítások'
          # body: 'a sonarqube elemzés által javasolt automatikus javítások.'
          # branch: sonarqube-fixes
          
  create-pr:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Commit SonarCloud changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply SonarCloud fixes"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Én a Sonar commitoltam ezen commitot"
        branch: "sonarcloud-fixes"
        title: "SonarCloud javasolt javítások"
        body: 'én, mint sonarqube javaslom eme javításokat'