name: SonarQube Analysis
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --no-restore
      
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: Build and analyze
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"kovesdinorbert_CodeCheck" /o:"kovesdinorbert" /d:sonar.host.url="${{ secrets.SONAR_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
          
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Én a Sonar commitoltam ezen commitot"
          branch: "sonarcloud-fixes"
          title: "SonarCloud javasolt javítások"
          body: 'én, mint sonarqube javaslom eme javításokat'
          
      
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: 'qodana scan'
        uses: jetbrains/qodana-action@v2023.3
        with: 
          args: --apply-fixes
          pr-mode: false
          push-fixes: pull-request
        env:
          qodana_token: ${{secrets.QODANA_TOKEN}}